Check pre-release versions on RubyGems

diff --git a/scripts/validate-monorepo-gem b/scripts/validate-monorepo-gem
--- a/scripts/validate-monorepo-gem
+++ b/scripts/validate-monorepo-gem
@@ -5,7 +5,13 @@ if [[ $# -ne 1 ]]; then
   exit 1
 fi
 
-if ! gem specification --remote --ruby "$1"; then
-  echo "The '$1' is missing. Push stub gem to RubyGems with version 0.0.1."
-  exit 1
+if gem specification --remote --ruby "$1"; then
+  exit 0
 fi
+
+if gem specification --remote --ruby --pre "$1"; then
+  exit 0
+fi
+
+echo "The '$1' is missing. Push stub gem to RubyGems with version 0.0.1."
+exit 1
