Google Cloud WLIF creation script to update integration detail
Additional improvements:
- verifies the PAT by making an API request
- makes the script more idempontent by checking existing resources

diff --git a/ee/lib/api/templates/google_cloud_integration_wlif_create.sh.erb b/ee/lib/api/templates/google_cloud_integration_wlif_create.sh.erb
--- a/ee/lib/api/templates/google_cloud_integration_wlif_create.sh.erb
+++ b/ee/lib/api/templates/google_cloud_integration_wlif_create.sh.erb
@@ -1,28 +1,76 @@
 #!/bin/bash
 
-set -eux
+set -eu
 set -o pipefail
 
-gcloud iam workload-identity-pools create <%= google_cloud_workload_identity_pool_id %> \
-  --project="<%= google_cloud_project_id %>" \
-  --location="global" \
-  --display-name="<%= google_cloud_workload_identity_pool_display_name %>"
+if [[ "${1:-}" == "--debug" ]]; then
+  set -x
+  shift
+fi
 
-# Verify the created Workload Identity Pool
-gcloud iam workload-identity-pools describe <%= google_cloud_workload_identity_pool_id %> \
-  --location="global" \
-  --project="<%= google_cloud_project_id %>"
+verify_gl_pat() {
+  if [ -z "${GL_PAT:-}" ]; then
+    echo "Error: The environment variable 'GL_PAT' is not set."
+    exit 1
+  fi
 
-gcloud iam workload-identity-pools providers create-oidc "<%= google_cloud_workload_identity_pool_provider_id %>" \
-  --location="global" \
-  --project="<%= google_cloud_project_id %>" \
-  --workload-identity-pool="<%= google_cloud_workload_identity_pool_id %>" \
-  --issuer-uri="<%= google_cloud_workload_identity_pool_provider_issuer_uri %>" \
-  --display-name="<%= google_cloud_workload_identity_pool_provider_display_name %>" \
-  --attribute-mapping="<%= google_cloud_workload_identity_pool_attribute_mapping %>"
+  RESPONSE_CODE=$(
+    curl -X GET "<%= api_integrations_url %>" \
+         --header "PRIVATE-TOKEN: $GL_PAT" \
+         --write-out "%{http_code}" \
+         -o /dev/null \
+    || true
+  )
+  if [ $RESPONSE_CODE -ne 200 ]; then
+    echo "Error: unable to access GitLab with the token provided in the GL_PAT environment variable."
+    exit 1
+  fi
+}
 
-# Verify the created OIDC provider for the Workload Identity Pool
-gcloud iam workload-identity-pools providers list \
-  --workload-identity-pool="<%= google_cloud_workload_identity_pool_id %>" \
-  --location=global \
-  --project="<%= google_cloud_project_id %>"
+create_google_cloud_resources() {
+  EXISTING_POOL=$(gcloud iam workload-identity-pools describe <%= google_cloud_workload_identity_pool_id %> --location="global" --project="<%= google_cloud_project_id %>" --format="value(name)" 2>/dev/null || true)
+  if [ -n "${EXISTING_POOL:-}" ]; then
+    echo "A Workload Identity Pool with the ID '%= google_cloud_workload_identity_pool_id %>' already exists. Skipping."
+  else
+    gcloud iam workload-identity-pools create <%= google_cloud_workload_identity_pool_id %> \
+      --project="<%= google_cloud_project_id %>" \
+      --location="global" \
+      --display-name="<%= google_cloud_workload_identity_pool_display_name %>"
+  fi
+
+  EXISTING_PROVIDER=$(gcloud iam workload-identity-pools providers describe "<%= google_cloud_workload_identity_pool_provider_id %>" --location="global" -project="<%= google_cloud_project_id %>" --workload-identity-pool="<%= google_cloud_workload_identity_pool_id %>" --format="value(name)" 2>/dev/null || true)
+  if [ -n "${EXISTING_PROVIDER:-}" ]; then
+    echo "A Provider with the ID '<%= google_cloud_workload_identity_pool_provider_id %>' already exists. Skipping."
+  else
+    gcloud iam workload-identity-pools providers create-oidc "<%= google_cloud_workload_identity_pool_provider_id %>" \
+      --location="global" \
+      --project="<%= google_cloud_project_id %>" \
+      --workload-identity-pool="<%= google_cloud_workload_identity_pool_id %>" \
+      --issuer-uri="<%= google_cloud_workload_identity_pool_provider_issuer_uri %>" \
+      --display-name="<%= google_cloud_workload_identity_pool_provider_display_name %>" \
+      --attribute-mapping="<%= google_cloud_workload_identity_pool_attribute_mapping %>"
+  fi
+}
+
+update_integration_data() {
+  GOOGLE_CLOUD_PROJECT_NUMBER=$(gcloud projects describe '<%= google_cloud_project_id %>' --format='value(projectNumber)')
+
+  JSON_PAYLOAD=$(cat <<EOF
+  {
+    "workload_identity_federation_project_id": "<%= google_cloud_project_id %>",
+    "workload_identity_federation_project_number": "$GOOGLE_CLOUD_PROJECT_NUMBER",
+    "workload_identity_pool_id": "<%= google_cloud_workload_identity_pool_id %>",
+    "workload_identity_pool_provider_id": "<%= google_cloud_workload_identity_pool_provider_id %>"
+  }
+EOF
+  )
+
+  curl -X PUT <%= api_wlif_integration_url %>  \
+       --header "Content-Type: application/json" \
+       --header "PRIVATE-TOKEN: $GL_PAT" \
+       --data "$JSON_PAYLOAD"
+}
+
+verify_gl_pat
+create_google_cloud_resources
+update_integration_data
